# Generated by Django 3.2.9 on 2021-11-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
    ]
